---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update repos
      dnf:
        update_cache: yes
      when: ansible_distribution == 'Fedora'

  tasks:
    - name: Enable the RPM Fusion repository
      dnf:
        name:
          - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
          - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
        state: present
        disable_gpg_check: True
      when: ansible_distribution == 'Fedora'


    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

    - name: Enable starship CORPS
      community.general.copr:
        state: enabled
        name: atim/starship
      when: ansible_distribution == 'Fedora'


    - name: install packages
      package:
        name:
          - stow
          - exa
          - gcc-c++
          - mpv
          - mpd
          - mpdris2
          - ncmpcpp
          - kitty
          - aria2
          - fish
          - neovim
          - fzf
          - alacritty
          - feh
          - starship
          - ripgrep
          - rust
          - cargo
          - qbittorrent
          - postgres-server
          - postgres-contrib
          - kernel-headers
          - kernel-devel
          - '@Development tools and libraries'

        name: Install flatpaks
        community.general.flatpak:
          name:
            - rest.insomnia.Insomnia
            - com.spotify.Client


    - name: python packages
      pip:
        name:
          - dbus-next

    - name: install pipx
      pip:
        name: pipx
        extra_args: --user

    - name: install beets
      become_user: pedro
      community.general.pipx:
        name: beets

    - name: install streamlink
      become_user: pedro
      community.general.pipx:
        name: streamlink

    - name: install yt-dlp
      become_user: pedro
      community.general.pipx:
        name: yt-dlp

    - name: install twofi
      become_user: pedro
      community.general.pipx:
        name: twofi
        source: git+https://github.com/Pecarvajal246/twofi

    - name: install fnm
      become_user: pedro
      community.general.cargo:
        name: fnm

    - name: dotfiles
      become_user: pedro
      git:
        repo: https://github.com/Pecarvajal246/.dotfiles.git
        dest: /home/pedro/.dotfiles/
        clone: yes

    - name: remove old bashrc
      file:
        path: /home/pedro/.bashrc
        state: absent

    - name: remove old profile
      file:
        path: /home/pedro/.profile
        state: absent

    - name: stow dotfiles
      shell:
        chdir: /home/pedro/.dotfiles/
        cmd: stow --restow *

    - name: copy scripts
      copy:
        src: scripts/
        dest: /home/pedro/.local/bin/
        directory_mode: a+x
        mode: a+x
        owner: pedro
